export const GET_FRIENDS_ATTEMPT = 'GET_FRIENDS_ATTEMPT';
export const GET_FRIENDS_SUCCESS = 'GET_FRIENDS_SUCCESS';
export const GET_FRIENDS_FAIL = 'GET_FRIENDS_FAIL';

export const GET_FRIENDS_SUGGESTIONS_ATTEMPT =
	'GET_FRIENDS_SUGGESTIONS_ATTEMPT';
export const GET_FRIENDS_SUGGESTIONS_SUCCESS =
	'GET_FRIENDS_SUGGESTIONS_SUCCESS';
export const GET_FRIENDS_SUGGESTIONS_FAIL = 'GET_FRIENDS_SUGGESTIONS_FAIL';

export const GET_FRIENDS_REQUESTS_ATTEMPT = 'GET_FRIENDS_REQUESTS_ATTEMPT';
export const GET_FRIENDS_REQUESTS_SUCCESS = 'GET_FRIENDS_REQUESTS_SUCCESS';
export const GET_FRIENDS_REQUESTS_FAIL = 'GET_FRIENDS_REQUESTS_FAIL';

export const REMOVE_FRIEND_ATTEMPT = 'REMOVE_FRIEND_ATTEMPT';
export const REMOVE_FRIEND_SUCCESS = 'REMOVE_FRIEND_SUCCESS';
export const REMOVE_FRIEND_FAIL = 'REMOVE_FRIEND_FAIL';

export const ADD_FRIEND_ATTEMPT = 'ADD_FRIEND_ATTEMPT';
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS';
export const ADD_FRIEND_FAIL = 'ADD_FRIEND_FAIL';

export const ACCEPT_FRIEND_REQUEST_ATTEMPT = 'ACCEPT_FRIEND_REQUEST_ATTEMPT';
export const ACCEPT_FRIEND_REQUEST_SUCCESS = 'ACCEPT_FRIEND_REQUEST_SUCCESS';
export const ACCEPT_FRIEND_REQUEST_FAIL = 'ACCEPT_FRIEND_REQUEST_FAIL';

export const DECLINE_FRIEND_REQUEST_ATTEMPT = 'DECLINE_FRIEND_REQUEST_ATTEMPT';
export const DECLINE_FRIEND_REQUEST_SUCCESS = 'DECLINE_FRIEND_REQUEST_SUCCESS';
export const DECLINE_FRIEND_REQUEST_FAIL = 'DECLINE_FRIEND_REQUEST_FAIL';

export const RESET_FRIENDS = 'RESET_FRIENDS';
export const RESET_FRIENDS_SUGGESTIONS = 'RESET_FRIENDS_SUGGESTIONS';
export const RESET_FRIENDS_REQUESTS = 'RESET_FRIENDS_REQUESTS';
