export const GET_GROUPS_ATTEMPT = 'GET_GROUPS_ATTEMPT';
export const GET_GROUPS_SUCCESS = 'GET_GROUPS_SUCCESS';
export const GET_GROUPS_FAIL = 'GET_GROUPS_FAIL';

export const GET_GROUP_ATTEMPT = 'GET_GROUP_ATTEMPT';
export const GET_GROUP_SUCCESS = 'GET_GROUP_SUCCESS';
export const GET_GROUP_FAIL = 'GET_GROUP_FAIL';

export const RESET_GROUPS = 'RESET_GROUPS';
export const RESET_SINGLE_GROUP = 'RESET_SINGLE_GROUP';
