export const GET_NOTIFICATIONS_COUNT = 'GET_NOTIFICATIONS_COUNT';
export const RESET_NOTIFICATIONS_COUNT = 'RESET_NOTIFICATIONS_COUNT';
export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';

export const GET_NOTIFICATIONS_ATTEMPT = 'GET_NOTIFICATIONS_ATTEMPT';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAIL = 'GET_NOTIFICATIONS_FAIL';

export const DELETE_NOTIFICATION_ATTEMPT = 'DELETE_NOTIFICATION_ATTEMPT';
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS';
export const DELETE_NOTIFICATION_FAIL = 'DELETE_NOTIFICATION_ATTEMPT';
