export const SET_OFFSET = 'SET_OFFSET';

export const GET_POSTS_ATTEMPT = 'GET_POSTS_ATTEMPT';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL';

export const GET_USERS_POSTS_ATTEMPT = 'GET_USERS_POSTS_ATTEMPT';
export const GET_USERS_POSTS_SUCCESS = 'GET_USERS_POSTS_SUCCESS';
export const GET_USERS_POSTS_FAIL = 'GET_USERS_POSTS_FAIL';

export const GET_POST_ATTEMPT = 'GET_POST_ATTEMPT';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAIL = 'GET_POST_FAIL';

export const CREATE_POST_ATTEMPT = 'CREATE_POST_ATTEMPT';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';

export const UPDATE_POST_ATTEMPT = 'UPDATE_POST_ATTEMPT';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL';

export const DELETE_POST_ATTEMPT = 'DELETE_POST_ATTEMPT';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';
