export const RESET_POSTS = 'RESET_POSTS';
export const RESET_SINGLE_POST = 'RESET_SINGLE_POST';

export const GET_POSTS_ATTEMPT = 'GET_POSTS_ATTEMPT';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL';

export const GET_USERS_POSTS_ATTEMPT = 'GET_USERS_POSTS_ATTEMPT';
export const GET_USERS_POSTS_SUCCESS = 'GET_USERS_POSTS_SUCCESS';
export const GET_USERS_POSTS_FAIL = 'GET_USERS_POSTS_FAIL';

export const GET_POST_ATTEMPT = 'GET_POST_ATTEMPT';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAIL = 'GET_POST_FAIL';

export const CREATE_POST_ATTEMPT = 'CREATE_POST_ATTEMPT';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';

export const UPDATE_POST_ATTEMPT = 'UPDATE_POST_ATTEMPT';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL';

export const DELETE_POST_ATTEMPT = 'DELETE_POST_ATTEMPT';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';

export const SHARE_POST_SUCCESS = 'SHARE_POST_SUCCESS';
export const SHARE_POST_FAIL = 'SHARE_POST_FAIL';

export const UNSHARE_POST_SUCCESS = 'UNSHARE_POST_SUCCESS';
export const UNSHARE_POST_FAIL = 'UNSHARE_POST_FAIL';

export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const LIKE_POST_FAIL = 'LIKE_POST_FAIL';

export const DISLIKE_POST_SUCCESS = 'DISLIKE_POST_SUCCESS';
export const DISLIKE_POST_FAIL = 'DISLIKE_POST_FAIL';

export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL';

export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS';
export const UPDATE_COMMENT_FAIL = 'UPDATE_COMMENT_FAIL';

export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';

export const JOIN_EVENT_SUCCESS = 'JOIN_EVENT_SUCCESS';
export const JOIN_EVENT_FAIL = 'JOIN_EVENT_FAIL';

export const LEAVE_EVENT_SUCCESS = 'LEAVE_EVENT_SUCCESS';
export const LEAVE_EVENT_FAIL = 'LEAVE_EVENT_FAIL';

export const ASKED_TO_JOIN_EVENT_SUCCESS = 'ASKED_TO_JOIN_EVENT_SUCCESS';
export const ASKED_TO_JOIN_EVENT_FAIL = 'ASKED_TO_JOIN_EVENT_FAIL';

export const ALLOW_TO_JOIN_EVENT_SUCCESS = 'ALLOW_TO_JOIN_EVENT_SUCCESS';
export const ALLOW_TO_JOIN_EVENT_FAIL = 'ALLOW_TO_JOIN_EVENT_FAIL';

export const REJECT_FROM_EVENT_SUCCESS = 'REJECT_FROM_EVENT_SUCCESS';
export const REJECT_FROM_EVENT_FAIL = 'REJECT_FROM_EVENT_FAIL';

export const REMOVE_FROM_REJECTED_SUCCESS = 'REMOVE_FROM_REJECTED_SUCCESS';
export const REMOVE_FROM_REJECTED_FAIL = 'REMOVE_FROM_REJECTED_FAIL';
